<?php
    $state_list = array('AL'=>"Alabama",
                'AK'=>"Alaska", 
                'AZ'=>"Arizona", 
                'AR'=>"Arkansas", 
                'CA'=>"California", 
                'CO'=>"Colorado", 
                'CT'=>"Connecticut", 
                'DE'=>"Delaware", 
                'DC'=>"District Of Columbia", 
                'FL'=>"Florida", 
                'GA'=>"Georgia", 
                'HI'=>"Hawaii", 
                'ID'=>"Idaho", 
                'IL'=>"Illinois", 
                'IN'=>"Indiana", 
                'IA'=>"Iowa", 
                'KS'=>"Kansas", 
                'KY'=>"Kentucky", 
                'LA'=>"Louisiana", 
                'ME'=>"Maine", 
                'MD'=>"Maryland", 
                'MA'=>"Massachusetts", 
                'MI'=>"Michigan", 
                'MN'=>"Minnesota", 
                'MS'=>"Mississippi", 
                'MO'=>"Missouri", 
                'MT'=>"Montana",
                'NE'=>"Nebraska",
                'NV'=>"Nevada",
                'NH'=>"New Hampshire",
                'NJ'=>"New Jersey",
                'NM'=>"New Mexico",
                'NY'=>"New York",
                'NC'=>"North Carolina",
                'ND'=>"North Dakota",
                'OH'=>"Ohio", 
                'OK'=>"Oklahoma", 
                'OR'=>"Oregon", 
                'PA'=>"Pennsylvania", 
                'RI'=>"Rhode Island", 
                'SC'=>"South Carolina", 
                'SD'=>"South Dakota",
                'TN'=>"Tennessee", 
                'TX'=>"Texas", 
                'UT'=>"Utah", 
                'VT'=>"Vermont", 
                'VA'=>"Virginia", 
                'WA'=>"Washington", 
                'WV'=>"West Virginia", 
                'WI'=>"Wisconsin", 
                'WY'=>"Wyoming",
                ''=>"-------------",
                'Alberta, Canada'=>"Alberta",
                'British Columbia, Canada'=>"British Columbia",
                'Manitoba, Canada'=>"Manitoba",
                'New Brunswick, Canada'=>"New Brunswick",
                'Newfoundland and Labrador, Canada'=>"Newfoundland and Labrador",
                'Nova Scotia, Canada'=>"Nova Scotia",
                'Northwest Territories, Canada'=>"Northwest Territories",
                'Nunavut, Canada'=>"Nunavut",
                'Ontario, Canada'=>"Ontario",
                'Prince Edward Island, Canada'=>"Prince Edward Island",
                'Quebec, Canada'=>"Quebec",
                'Saskatchewan, Canada'=>"Saskatchewan",
                'Yukon, Canada'=>"Yukon");
    ?>
<?= $this->headScript() ?> 
<?= $this->headLink() ?>
<div id="login-form" style="max-width:600px;">
<form class="form-signin" autocomplete="off" method="POST">
<!--    	<img src="<?php echo $this->baseUrl();?>/images/login-logo.png" alt="charlie palmer group cms" />-->
<!--        <img src="<?php echo $this->baseUrl();?>/images/logo-g.png"/>-->
    <img src="<?php echo $this->baseUrl();?>/images/logo_w.png" style="height:50px;margin-bottom: 30px;"/>
            <div style="margin-bottom:20px;"></div>
            <div class="row-fluid">
               <div class="span6"> 
                   <label>Campaign Name &nbsp;(cannot be changed later)</small></label>
            
        <input type="text" style="margin-bottom:0 !important;padding:0px 10px;" maxlength="100" id="input-campaign"  class="input-block-level" placeholder="e.g. 2015 John Smith For Senate">
         <label style="margin-top:10px;">Election Date</label>
         <input type="text" style="margin-bottom:0 !important; width:120px; cursor:pointer !important;padding:0px 10px;" maxlength="100" id="input-date"  class="input-block-level">
         <label style="margin-top:10px;">State/Province</label>
         <select id="input-state" style="width:120px; margin-bottom:0 !important;">
             <option value=""></option>
                                        <?php 
                                        foreach($state_list as $key => $value){
                                            echo '<option value="'. $key . '">'. $value .'</option>';
                                        }
                                        ?>
         </select>
            </div><div class="span6">
         <label>City or County (if applicable)</label>
        <input type="text" style="margin-bottom:0 !important;padding:0px 10px;" maxlength="96" id="input-city" class="input-block-level">
         <label style="margin-top:10px;">New Password</label>
        <input type="password" style="margin-bottom:0px !important;padding:0px 10px;" maxlength="500" id="input-password" class="input-block-level" placeholder="8 Characters">
        <label style="margin-top:10px;">Confirm Password</label>
        <input type="password" style="margin-bottom:20px !important;padding:0px 10px;" maxlength="500" id="input-confirm" class="input-block-level" >
        
        <button class="btn btn-primary pull-right" id="btn-submit">Next</button>
            </div></div>
</form>
</div>